# Generated by Django 5.1.7 on 2025-05-03 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_modelo_remove_veiculo_marca_remove_veiculo_cor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='categoria',
        ),
        migrations.AddField(
            model_name='veiculo',
            name='cor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.cor', verbose_name='Cor'),
            preserve_default=False,
        ),
    ]
